### PR TITLE
stories history

### PR DESCRIPTION
**Pull request by rastislav-chynoransky**

### CODE REVIEW

**Review by igor-kamil — COMMENTED** [review]
works nicely. only the animation of "tap to collect artworks" on every return back to story is bit annoying. any idea, how to fix that?

**Comment by rastislav-chynoransky** [comment]
> works nicely. only the animation of "tap to collect artworks" on every return back to story is bit annoying. any idea, how to fix that?

I've added to the stories store.

**Comment by rastislav-chynoransky** [comment]
Let's just disable it completely since it glitches on mobile devices. We'll fix it in another issue.

**Review by igor-kamil — APPROVED** [review]
👌

**Pull request merged**
